console.log("Wait, looking at the code in the prompt:");
console.log("```typescript");
console.log("            }");
console.log("        }");
console.log("    }");
console.log("    throw new Error('Max retries exceeded');");
console.log("}");
console.log("");
console.log("/**");
console.log(" * プレイリスト一覧を取得");
console.log(" */");
console.log("export function usePlaylists() {");
console.log("    const { data: session } = useSession();");
console.log("    const userEmail = session?.user?.email;");
console.log("");
console.log("    return useQuery({");
console.log("        queryKey: [\"playlists\", userEmail],");
console.log("        queryFn: async () => {");
console.log("            return retryFetch<PlaylistWithItems[]>(() => fetch(\"/api/playlists\"));");
console.log("        },");
console.log("        enabled: !!userEmail,");
console.log("    });");
console.log("```");
console.log("The test coverage report showed:");
console.log("usePlaylists.ts             |   98.83 |      100 |     100 |   98.78 | 27");
console.log("Line 27 is the `throw new Error('Max retries exceeded');` statement.");
