import { render, screen, act } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { PlaybackSpeedDial } from "../PlaybackSpeedDial";

describe("PlaybackSpeedDial", () => {
  const defaultProps = {
    open: true,
    value: 1.0,
    onValueChange: jest.fn(),
    onOpenChange: jest.fn(),
  };

  beforeAll(() => {
    // Mock setPointerCapture as it is not implemented in JSDOM
    window.HTMLElement.prototype.setPointerCapture = jest.fn();
    window.HTMLElement.prototype.releasePointerCapture = jest.fn();
  });

  beforeEach(() => {
    jest.clearAllMocks();

    // reset scroll / bounding mocks
    Element.prototype.getBoundingClientRect = jest.fn(() => {
      return {
          width: 640,
          height: 100,
          top: 0,
          left: 0,
          bottom: 0,
          right: 0,
          x: 0,
          y: 0,
          toJSON: () => {}
      }
    })
  });

  it("should not render when open is false", () => {
    render(<PlaybackSpeedDial {...defaultProps} open={false} />);
    expect(screen.queryByText("再生速度")).toBeNull();
  });

  it("should render correctly when open is true", () => {
    render(<PlaybackSpeedDial {...defaultProps} />);
    expect(screen.getByText("再生速度")).toBeInTheDocument();

    // Get all elements containing "1.0x" and find the one that is the actual current speed display
    const elements = screen.getAllByText("1.0x");
    // Since there are multiple, verify at least one is rendered
    expect(elements.length).toBeGreaterThan(0);

    expect(screen.getByTestId("speed-option-1.0")).toBeInTheDocument(); // Speed option
  });

  it("should call onOpenChange with false when clicking the backdrop", async () => {
    const user = userEvent.setup();
    const { container } = render(<PlaybackSpeedDial {...defaultProps} />);

    // The backdrop is the first div
    const backdrop = container.firstChild as HTMLElement;
    await user.click(backdrop);

    expect(defaultProps.onOpenChange).toHaveBeenCalledWith(false);
  });

  it("should call onValueChange and onOpenChange when clicking a speed option", async () => {
    const user = userEvent.setup();
    render(<PlaybackSpeedDial {...defaultProps} />);

    const option1_5x = screen.getByTestId("speed-option-1.5");
    await user.click(option1_5x);

    expect(defaultProps.onValueChange).toHaveBeenCalledWith(1.5);
    expect(defaultProps.onOpenChange).toHaveBeenCalledWith(false);
  });

  it("should call onOpenChange with false when pressing Escape", async () => {
    const user = userEvent.setup();
    render(<PlaybackSpeedDial {...defaultProps} />);

    await user.keyboard("{Escape}");

    expect(defaultProps.onOpenChange).toHaveBeenCalledWith(false);
  });

  describe("keyboard navigation on track", () => {
    // We use exactly the value generated by `0.8 + 4 * 0.1` to match the exact float.
    const speeds = Array.from({ length: 23 }, (_, i) => 0.8 + i * 0.1);
    const speed1_2 = speeds[4]; // ~1.2

    it("should decrease speed on ArrowLeft", async () => {
        const user = userEvent.setup();
        render(<PlaybackSpeedDial {...defaultProps} value={speed1_2} />);

        const track = screen.getByRole("slider");
        track.focus();
        await user.keyboard("{ArrowLeft}");

        expect(defaultProps.onValueChange).toHaveBeenCalledWith(speeds[3]);
    });

    it("should increase speed on ArrowRight", async () => {
        const user = userEvent.setup();
        render(<PlaybackSpeedDial {...defaultProps} value={speed1_2} />);

        const track = screen.getByRole("slider");
        track.focus();
        await user.keyboard("{ArrowRight}");

        expect(defaultProps.onValueChange).toHaveBeenCalledWith(speeds[5]);
    });

    it("should decrease speed on ArrowDown", async () => {
        const user = userEvent.setup();
        render(<PlaybackSpeedDial {...defaultProps} value={speed1_2} />);

        const track = screen.getByRole("slider");
        track.focus();
        await user.keyboard("{ArrowDown}");

        expect(defaultProps.onValueChange).toHaveBeenCalledWith(speeds[3]);
    });

    it("should increase speed on ArrowUp", async () => {
        const user = userEvent.setup();
        render(<PlaybackSpeedDial {...defaultProps} value={speed1_2} />);

        const track = screen.getByRole("slider");
        track.focus();
        await user.keyboard("{ArrowUp}");

        expect(defaultProps.onValueChange).toHaveBeenCalledWith(speeds[5]);
    });

    it("should set to minimum speed on Home", async () => {
        const user = userEvent.setup();
        render(<PlaybackSpeedDial {...defaultProps} value={speed1_2} />);

        const track = screen.getByRole("slider");
        track.focus();
        await user.keyboard("{Home}");

        expect(defaultProps.onValueChange).toHaveBeenCalledWith(speeds[0]);
    });

    it("should set to maximum speed on End", async () => {
        const user = userEvent.setup();
        render(<PlaybackSpeedDial {...defaultProps} value={speed1_2} />);

        const track = screen.getByRole("slider");
        track.focus();
        await user.keyboard("{End}");

        expect(defaultProps.onValueChange).toHaveBeenCalledWith(speeds[speeds.length - 1]);
    });
  });
});
